# Workflow polegający na instalacji Pythona, jego zależności oraz utworzenia pliku .exe za pomocą pyinstaller.

name: Python - Build with PyInstaller

on:
  push:
    # Automatycznie po pushowaniu na mastera (maina)
    branches: [ "main" ]
  pull_request:
    # Uzupełnienie do pusha, jako że głównie działam na pull requestach
    branches: [ "main" ]
  schedule:
    # Automatycznie raz w tygodniu (dzień i godzina dowolna) - wybrany każdy Piątek o 04:20
    - cron:  '20 4 * * 5'
  label:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    # Ustawienie domyślnego serwera Windows (najnowszy dostępny) - aktualnie jest to 2022
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Build using powershell # W środku zawarte są już instrukcje o pyinstaller
      run: |
        .\buildme.ps1
    # Wykorzystanie action/upload-artifact@v3 (v3 jest wktórce deprecjonowane, użyłem v4) do przesłania utworzonego pliku .exe na repozytorium github
    - name: Dodaj utworzony plik .exe do repozytorium
      uses: actions/upload-artifact@v4.3.4
      with:
        name: Executable
        path: .\dist\konwerter.exe
        if-no-files-found: warn
        overwrite: true
    - name: Struktura plików dla .exe
      run: |
        mkdir -Force artefacts
        Remove-Item -Force .\artefacts\konwerter.exe
        Move-Item .\dist\konwerter.exe .\artefacts\konwerter.exe
        git add .\artefacts\konwerter.exe
    - name: Scommituj artefakt bezpośrednio do repozytorium
      uses: stefanzweifel/git-auto-commit-action@v5.0.1
      with:
        commit_message: Automatyczne dodanie nowej wersji pliku .exe
        branch: main
        commit_options: '--no-verify --signoff'
        commit_author: Author <actions@github.com>
        status_options: '--untracked-files=no'
        skip_dirty_check: true
